version: '3'

services:
  samba:
    image: dperson/samba
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    restart: unless-stopped
    environment:
        - USERNAME=${USERNAME}
        - PASSWORD=${PASSWORD}
    volumes:
      - ./share:/srv:z
    command: "-u \"${USERNAME};${PASSWORD}\" -s \"share;/srv;yes;yes;yes;${USERNAME}\" -p"
